CREATE TABLE screen (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE recipe (
  id INTEGER NOT NULL AUTO_INCREMENT,
  idScreen INTEGER NOT NULL,
  number INTEGER NOT NULL,
  FOREIGN KEY (idScreen) REFERENCES screen(id) ON DELETE RESTRICT,
  PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ingredient (
  id INTEGER NOT NULL AUTO_INCREMENT,
  idRecipe INTEGER NOT NULL,
  amount FLOAT NOT NULL,
  name VARCHAR(255) NOT NULL,
  unit VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  FOREIGN KEY (idRecipe) REFERENCES recipe(id) ON DELETE RESTRICT,
  PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

