CREATE TABLE duplicate (
  id INTEGER NOT NULL AUTO_INCREMENT,
  idScreen1 INTEGER NOT NULL,
  idScreen2 INTEGER NOT NULL,
  idRecipe1 INTEGER NOT NULL,
  idRecipe2 INTEGER NOT NULL,
  comparatorString VARCHAR(255) NOT NULL,
  FOREIGN KEY (idScreen1) REFERENCES screen(id) ON DELETE RESTRICT,
  FOREIGN KEY (idScreen2) REFERENCES screen(id) ON DELETE RESTRICT,
  FOREIGN KEY (idRecipe1) REFERENCES recipe(id) ON DELETE RESTRICT,
  FOREIGN KEY (idRecipe2) REFERENCES recipe(id) ON DELETE RESTRICT,
  PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;