var PICKScreensConfig = {};
PICKScreensConfig.ENABLE_MIN_SCREENS = 2;
PICKScreensConfig.ENABLE_MAX_SCREENS = 200;
PICKScreensConfig.BUTTON_CROSS_TABLE_MIN_SCREENS = PICKScreensConfig.ENABLE_MIN_SCREENS;
PICKScreensConfig.BUTTON_CROSS_TABLE_MAX_SCREENS = PICKScreensConfig.ENABLE_MAX_SCREENS;